### ISSUE TITLE
index is not defined

### ISSUE THREAD

**Issue by valentina-paniza** [xwatkins/vcf-to-json#2]
Hi there! i'm having an issue on line:
const json = await index.vcfToJson(fileContent);

'ReferenceError: index is not defined'

Any ideas on why i'm getting that problem? Are there any dependencies that need to be installed?
Thank you in advance!

**Comment by xwatkins** [comment]
Hi @valentina-paniza - there seems to be a typo in the example. Please try:

`const json = await vcfToJSON(fileContent);`

Let me know if that works for you and will update the doc.
